### ISSUE TITLE
Nav bar too busy needs to be redesigned

### ISSUE THREAD

**Issue by xander-miller** [xander-miller/ProjectNightMeta#14]
At this point our app does very little but our nav bar looks unnecessarily busy when a user is logged in. We need the nav bar to be simple and clean. Some ideas how to clean things up:
- Sign In / User Name to the right edge
- Remove general groups from the nav bar, it's a redundant view with Meetup. If they want to look for groups to join they can use Meetup. 
- My Groups and My Projects should appear between the page title and About bumping About down the line. 
- Settings should become a menu item under the logged in User name or be replaced by an icon (preferably a gear that appears next to the logged in user name.
- Logged in user Avatar pic should appear just before the user's name.

**Comment by fun-ruby** [comment]
General Groups link is removed from nav bar in pull request #15

**Comment by xander-miller** [comment]
Nice, Long.
I did the rest of the stuff in latest commit, except the tiny Avatar. Couldn't figure out how to access the current user from the navbar I was also concerned that the mu_thumb_link image would prove too big for the task. In the end I thought there were high priority concerns. 
I was only messing with front end. If I do anything with models or controllers, I will push to a branch.

**Comment by fun-ruby** [comment]
The thumb can be a nice touch for web but may not be as mobile friendly. I would like us to target mobile as a first priority and web a second since going the other way will require more work.

Also I am not sure it is necessary to move the nav bar in to a partial. Generally partial are slower to render so I would suggest keeping its use to a minimum.

**Comment by xander-miller** [comment]
It makes sense the transitioning a design to a large view area from a smaller view area would be easier than the other way around. Unfortunately I don't know much about responsive design. 

I'll close the thumb in the navbar issue. It's a unnecessary distraction.

Of course too much of anything can be bad but I think the using a partial in this way modulizes the code and makes it more readable. It is also recommend by [Rails Guide: Layouts 3.4.2](http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials). If we have performance issues down the road it is easy to undo.

**Comment by fun-ruby** [comment]
I just think partial is mis-used in this case. The nav bar is displayed in all site pages and is more or less static so it makes less sense to me.

In practice, I use partial to share a section in several pages so copies of it are not pasted in verbatim. I don't see us doing this in this case.

**Comment by xander-miller** [comment]
I agree the best use of partials is to keep things DRY but I still think it is valid to use partials to modularize your code semantically to make it more readable and easy to find things.
