### ISSUE TITLE
Is there a URL where this is being hosted?

### ISSUE THREAD

**Issue by RangerMauve** [xander-miller/ProjectNightMeta#31]
By the looks of it this thing is semi-semi-functional, is it deployed somewhere on Heroku or something? Maybe a link in the README would be a good idea.

**Comment by xander-miller** [comment]
Here:

http://sleepy-sea-2672.herokuapp.com/

It's not up to date with the code base though. I should put up an up to date one. @fun-ruby put that one up. I'll add a link to the read me when there is an updated deploy.
